### ISSUE TITLE
Use SettingsModal to store extension settings

### ISSUE THREAD

**Issue by tituspijean** [tituspijean/flarum-ext-auth-ldap#1]
Use SettingsModal class to store LDAP server options

**Comment by TitusPiJean** [comment]
Current admin form and settings are relics from the SAML2 extension from which was the initial commit.

**Comment by tituspijean** [comment]
b7e8dd2 updated the settings, but SettingsModal does not show up.

**Comment by tituspijean** [comment]
e8887d8 circumvents the issue by creating a SettingsPage instead of a SettingsModal.
