### ISSUE TITLE
Fixes for 0.1.0-beta.8+

### ISSUE THREAD

**Issue by tituspijean** [tituspijean/flarum-ext-auth-ldap#11]
Version 0.1.0-beta.8 will introduce several changes in the backend of Flarum.
For this extension we will have to pay attention to:

- [x] [Changes in the namespaces](https://discuss.flarum.org/d/6572-help-us-namespace-changes)

**Comment by tituspijean** [comment]
Hiiiiya: https://discuss.flarum.org/d/6573-convert-your-beta-7-compatible-extension-to-work-on-beta-8

**Comment by popindavibe** [comment]
Did you manage to get it working? I gave it a go few weeks back, but it broke the LDAP authentication and I had to restore from backup eventually...

**Comment by tituspijean** [comment]
I did not try since the release of beta 8, because I developed this extension for the YunoHost package of Flarum which is not compatible with PHP 7.2 apps.
I realize now that people can also use it directly. I will give it a try in the following days.

**Comment by nadi106** [comment]
hey, any progress made?

**Comment by tituspijean** [comment]
Right now the extension works, but needs some polishing:

- [ ] The JS payload sent by the AuthenticationFactory is considered an error, but it should be executed to automatically close the LoginModal and refresh the page.
- [ ] The setting to customize the "Log in with..." link is not found.

**Comment by nadi106** [comment]
Will this work with flarum beta 10?

**Comment by tituspijean** [comment]
Yes obviously, note the "+" after "beta8" in the title. 😉
