### ISSUE TITLE
Allow to alter how the DN is built (do not only rely on uid)

### ISSUE THREAD

**Issue by Ornanovitch** [tituspijean/flarum-ext-auth-ldap#17]
Hi ! Thank you for this extension, I'm configuring a flarum instance and ldap is the only way my users will log in.

I tried to configure the extension, but all my attempts are failing with no error. Only this in the firefox console : 

```
TypeError: this.ldaplogin(...) is undefined LDAPLogInModal.js:165:9
    onsubmit LDAPLogInModal.js:165
    onsubmit self-hosted:1019
    L/t[e]< mithril.js:1286
```
 My access.log : 

`POST /auth/ldap HTTP/1.1" 500`

php-ldap is installed, I have no other clue...

**Comment by tituspijean** [comment]
Hi, thanks for your feedback!
Do you have any error in your PHP logs, server side?

**Comment by Ornanovitch** [comment]
In debug mode, this appears : 

![Screenshot_2019-11-27 Whoops There was an error ](https://user-images.githubusercontent.com/34077099/69723496-fd50b180-1119-11ea-9258-2e4aba4d6d45.png)

In my php-fpm.log, nothing.

In my nginx/error.log, I have all this but I had already those messages before installing your extension : 

```
2019/11/27 13:30:20 [error] 17741#17741: *103 open() "/var/www/flarum/public/service-worker-29f380effd40cdaa98cfa88ea74b0c66ba6ca6c901f666253c7592d49fa5e7d4.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /service-worker-29f380effd40cdaa98cfa88ea74b0c66ba6ca6c901f666253c7592d49fa5e7d4.js HTTP/1.1", host: "talk.felinn.org"
2019/11/27 13:30:20 [error] 17741#17741: *104 open() "/var/www/flarum/public/javascripts/workbox/workbox-sw.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /javascripts/workbox/workbox-sw.js HTTP/1.1", host: "talk.felinn.org"
2019/11/27 13:30:20 [error] 17741#17741: *105 open() "/var/www/flarum/public/javascripts/workbox/workbox-routing.prod.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /javascripts/workbox/workbox-routing.prod.js HTTP/1.1", host: "talk.felinn.org"
2019/11/27 13:30:20 [error] 17741#17741: *106 open() "/var/www/flarum/public/javascripts/workbox/workbox-core.prod.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /javascripts/workbox/workbox-core.prod.js HTTP/1.1", host: "talk.felinn.org"
2019/11/27 13:30:20 [error] 17741#17741: *107 open() "/var/www/flarum/public/javascripts/workbox/workbox-strategies.prod.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /javascripts/workbox/workbox-strategies.prod.js HTTP/1.1", host: "talk.felinn.org"
2019/11/27 13:30:20 [error] 17741#17741: *108 open() "/var/www/flarum/public/javascripts/workbox/workbox-expiration.prod.js" failed (2: No such file or directory), client: 192.168.10.100, server: talk.felinn.org, request: "GET /javascripts/workbox/workbox-expiration.prod.js HTTP/1.1", host: "talk.felinn.org"

```

**Comment by tituspijean** [comment]
OK, I think the extension is not listening to all the errors the LDAP binding can throw. You hence get a generic error.

- Can you try to see what triggers this error? In debug mode, you should be able to "rewind" the stack of commands to led to it.
- Can you check all your settings? (try to do an ldap search via command line for example)
- Try also not to use the admin authentication, I am doubting it actually works.

**Comment by Ornanovitch** [comment]
Thanks again !

I tried without admin auth, without change.

> Can you try to see what triggers this error? In debug mode, you should be able to "rewind" the stack of commands that led to it.

I can't identify what exactly triggers the error. Here are the 3 last commands before the error : 

![1](https://user-images.githubusercontent.com/34077099/69797413-eff5fe80-11cf-11ea-96c2-a311990c9d54.png)
![2](https://user-images.githubusercontent.com/34077099/69797422-f2f0ef00-11cf-11ea-89e3-a50a9a6472af.png)
![3](https://user-images.githubusercontent.com/34077099/69797425-f5534900-11cf-11ea-81e0-306021aff996.png)
![4](https://user-images.githubusercontent.com/34077099/69797429-f7b5a300-11cf-11ea-83f4-18eaaabf34b2.png)
![5](https://user-images.githubusercontent.com/34077099/69797439-fdab8400-11cf-11ea-9421-748caa400154.png)
![6](https://user-images.githubusercontent.com/34077099/69797452-03a16500-11d0-11ea-9649-d9c464b149b2.png)

> Can you check all your settings? (try to do an ldap search via command line for example)

What exactly should I be searching for ? Files ? Paths ?

I don't know if it can helps, but here is our gitlab ldap configuration (working fine), I tried to adapts it for flarum : 

```
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
  main: # 'main' is the GitLab 'provider ID' of this LDAP server
    label: 'FELINN'
    host: '192.168.10.113'
    port: 389
    uid: 'uid'
    bind_dn: 'cn=fd-admin,dc=felinn,dc=org'
    password: '****************************'
    encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
    verify_certificates: true
    active_directory: true
    allow_username_or_email_login: true
    lowercase_usernames: false
    block_auto_created_users: false
    base: 'dc=felinn,dc=org'
    user_filter: '(objectclass=person)'
    ## EE only
    group_base: ''
    admin_group: ''
    sync_ssh_keys: false
```

Flarum config :
```

method_name : FELINN
hosts : 192.168.10.113
base_dn : dc=felinn,dc=org
port : 389
account_prefix : objectclass=person
account_suffix :
follow_referrals (oui/non) : no
use_ssl (oui/non) :  no
use_tls (oui/non) :  no
use_admin (oui/non) : no
admin_dn (oui/non) :  no
admin_password (oui/non) : no
onlyUse (oui/non) : no

```

Note that I'm not an ldap expert...

**Comment by tituspijean** [comment]
Try emptying the `account_prefix`, it is not meant as a filter.
Basically if your user id is `ornanovitch`, then it would end up looking for `objectclass=personornanovitch`.

I will investigate if it's possible to implement this filter in the extension, but it would work without it.

**Comment by Ornanovitch** [comment]
OK, thanks. I emptied `account_prefix`, now there is only

```
method_name : FELINN
hosts : 192.168.10.113
base_dn : dc=felinn,dc=org
port : 389
```
So in theory I guess it should give access and create an user in DB for all members referenced into the `base_dn` ? It would be a first victory, but for now the same error remains...

**Comment by tituspijean** [comment]
No, what it does is using the username and password given in Flarum's login modal to connect into the LDAP server as this user. If the connection is successful, then it creates the same user in Flarum's database.

I will try to investigate tonight, I am at a loss about the next steps.

Note to self: write an actual README. :)

**Comment by tituspijean** [comment]
Hi, to help me debug the issue, can you delete these two lines?
https://github.com/tituspijean/flarum-ext-auth-ldap/blob/d88361a1e3b26139097d881a86a4d15183c817db/src/Controllers/LDAPAuthController.php#L77-L78

The file should be in `${your_flarum_path}/vendor/tituspijean/flarum-ext-auth-ldap/src/Controllers/LDAPAuthController.php`. Then post the debug screen.

**Comment by Ornanovitch** [comment]
The error is more verbose now : 
`No LDAP query results for filter: [(objectclass=*)] in: [uid=ornano,dc=felinn,dc=org]`

**Comment by tituspijean** [comment]
Weird. I really do not know what is the matter. 
Can you try binding with the admin account again?

**Comment by nadi106** [comment]
Implementing this extension in my environment let me to the conclusion that the search is not being done recursively within the directories. 
I think that changing the `base_dn` in your case to `cn=fd-admin,dc=felinn,dc=org` will work.

**Comment by Ornanovitch** [comment]
> Can you try binding with the admin account again?

Same problem...

> I think that changing the base_dn in your case to cn=fd-admin,dc=felinn,dc=org will work.

It does not, but thanks for helping me !

Should I try your solution @nadi106 ? How would I implement this ? In `LDAPAuthController.php`, replacing lines 53-54 ? : 
```
      $provider->auth()->attempt($uid_dn, $password, $bindAsUser = true);
      $user = $provider->search()->findByDnOrFail($uid_dn);
```

**Comment by Ornanovitch** [comment]
OK, I tried to implement your modifications, it brings me to this error : 
`could not bind to ldap server`

**Comment by nadi106** [comment]
@Ornanovitch what OS are you on?

**Comment by Ornanovitch** [comment]
Debian 9 !

>  Also, it matters on which line this error occurred, can you send more info?

This one (the last one) :

`throw new Exception("Could not bind to LDAP server")`

**Comment by nadi106** [comment]
> Debian 9 !
I was on Ubuntu when integrating this and I found using `ldapsearch` package to test some queries helpful. You should try that.

**Comment by Ornanovitch** [comment]
OK, I'll do that, thanks !

**Comment by Ornanovitch** [comment]
Solved ! :fireworks: 

So, we have investigated a lot with my mates, here is what's happening : 

[adLDAP](http://adldap.sourceforge.net/) wants to have user's `dn` referenced by `uid`, like this : 

```shell
ldapsearch -H ldap:// -x  -b "uid=<uid>,ou=people,dc=felinn,dc=org"
```
But in our LDAP configuration, the user's `dn` was referenced by `cn` (last name + surname). We didn't want this but it seemed to be a default configuration that we didn't see.

So we had to change the default configuration in fusion directory (`configuration`, `people and group storage`), but as it's not a backdated action, we also had to change manually existing users with a script as explained [here](https://www.digitalocean.com/community/tutorials/how-to-use-ldif-files-to-make-changes-to-an-openldap-system) : 

```ldif
dn: cn=<actual user's cn variabl>,ou=<if you have one by default>,dc=foo,dc=bar
changetype: modrdn
newrdn: uid=<username>
deleteoldrdn: 0
newsuperior: ou=<no change>,dc=foo,dc=bar
```
Then we pass the script throught command line :

```shell
ldapmodify -x -D "cn=admin,dc=foo,dc=bar" -w <password> -H ldap:// -f <script>.ldif
```
Now every LDAP user can sign up in our flarum ! :+1: 

It's interesting because it suggests that we would have achieve this if there were some other options in your extension, like filters. But it allowed us to understand that we had a bad practice with this user's `dn` option (because we had to register name and surname of all our users, witch is not our desire). At least, I think it's important for admins to know that they should have user's `dn` mapped with `uid` in their LDAP configuration to use this extension.

Thanks a lot for all your help, and thanks for this extension !

**Comment by tituspijean** [comment]
I am glad you solved the issue, and I am sorry you had to change your LDAP setup to accommodate this extension's flaws. If that's already with you, I am keeping this issue open to try to implement versatile DN configurations.

I will investigate the matter, but on first thoughts providing a `uid` is mandatory for Flarum. It is tricky to identify users only by their `cn` since it can change! (I am thinking about marriage, legal name change, etc.)
