### ISSUE TITLE
Flarum\Event\ConfigureMiddleware is now deprecated for beta.12

### ISSUE THREAD

**Issue by tituspijean** [tituspijean/flarum-ext-auth-ldap#18]
[Flarum beta.12 has been released](https://github.com/flarum/flarum/releases/tag/v0.1.0-beta.12)
[Changelog](https://discuss.flarum.org/d/22973-flarum-010-beta12-released)

~~⚠️ `Flarum\Event\ConfigureMiddleware` is now deprecated.~~ It is not used in this extension.

**Comment by Ornanovitch** [comment]
Hey @tituspijean !

Hope you're doing well. Any news regarding the compatibility with beta 12 ?
I had to reinstall all my extensions recently, and with composer, flarum-ext-auth-ldap `requires flarum/core >=0.1.0-beta.10 <0.1.0-beta.12`

regards,

**Comment by tituspijean** [comment]
Hi @Ornanovitch, after some testing, it seems I do not need much work here: I only had to bump up the required versions. If you are willing to help me test it, I have created a [pre-release for beta.12](https://github.com/tituspijean/flarum-ext-auth-ldap/releases/tag/v0.1.0-beta.12), let me know if anything goes wrong.

**Comment by Ornanovitch** [comment]
Thanks you !

I begin the test, for now it's working with my first config. I have to test another ldap server in several days, so it will be the opportunity for a complete test. I let you know !
