### ISSUE TITLE
`memberof` filter problem

### ISSUE THREAD

**Issue by Ornanovitch** [tituspijean/flarum-ext-auth-ldap#20]
Hey @tituspijean !

Here is a first issue I have with my new LDAP config on beta-12.

My `Base_dn` is `memberof=cn=talk,ou=groups,dc=foo,dc=foo`

My ldap receives a bad request with the second `=` of the `memberOf` filter, which is interpreted as a `\3D` (?!) :

`cannot find entry: "uid=ornano,memberOf=cn\3Dtalk,ou=groups,dc=foo,dc=foo`

Without memberOf, if I give others basic filters, it's working fine. But I will have to apply a filter, as I want that only users who are members of our `talk` ldap group can access to flarum.

Thanks again !

**Comment by tituspijean** [comment]
Indeed, something like `memberof=cn=...` will not work. Whatever between an equal sign and the next comma will be expected to be text. So your second equal sign is transliterated into its corresponding code.

If you don't use `cn`, can you try the following? (frankly I am not sure it will work) 
```memberof=talk,ou=groups,dc=foo,dc=foo```

I will look into adding filters this weekend.

**Comment by Ornanovitch** [comment]
OK, thanks for the explanation !

Indeed, `memberOf=talk` does not work

**Comment by tituspijean** [comment]
Hi @Ornanovitch, I have just created a test release (v0.1.0-beta.12-1) with the filter feature added. 
The user discovery flow is: LDAP -> Filter -> UID with base DN. Hopefully they cascade without any issue.

I have no means to test it, so can you report if it is working on your side?

**Comment by Ornanovitch** [comment]
Hi @tituspijean, thanks for starting to work on this improvement !

I'd be happy to test it in a few days, I let you know how it's working asap :)

**Comment by tituspijean** [comment]
I have successfully tested the filter on my side, everything seems alright. Do not hesitate to reopen if you have any issue.

**Comment by Ornanovitch** [comment]
Hey @tituspijean, sorry for the long time before reaction !

I just tested your improvements, but I have a problem : whatever I put in the filter field, the controller returns `This user is not allowed to log in.` but when I watch into the ldap logs, it doesn't even queries my ldap server... When I enter the old config (without filter), it queries my ldap without problem.

Can you tell me how you did your test ?

**Comment by tituspijean** [comment]
I use YunoHost as server, which can assign permissions (ie groups) to users. I my tests, with the following filter, only users with the `flarum.login` permission could log in with LDAP.

`(&(objectClass=posixAccount)(permission=cn=flarum.login,ou=permission,dc=yunohost,dc=org)`

Based on your previous comments, I guess your filter should be something like:
(&(memberOf=cn=talk,ou=groups,dc=foo,dc=foo)`

(again, I am not a pro at LDAP'ing, so sorry if I mislead you)

**Comment by Ornanovitch** [comment]
Thank you very much, it was a simple syntax mistake :)

It works like a charm ! I have an other little issue which doesn't concerns filter, so I'm gonna open a new issue for this.

Thanks again, great work !
