### ISSUE TITLE
How to debug failing ldap connection?

### ISSUE THREAD

**Issue by Marty** [tituspijean/flarum-ext-auth-ldap#23]
Hi,
after installing beta 12-1 I configured the plugin with my configuration that is working in other systems, but on login I only get a popup saying "An error occurred while trying to load this page.".

Nothing in the docker container logs and nothing in the nginx logs.

My php and nginx skills are "limited", how can I further debug this issues?
Regards

```
Domains: ldap.host.limited
Base DN: ou=users,dc=host,dc=limited
Filter: (&(objectClass=inetOrgPerson)(memberOf=cn=active,ou=groups,dc=host,dc=limited))
Port: 389
Use TLS: true
Connect with admin account: true
Admin name: cn=flarum,ou=bots,dc=host,dc=limited
```

**Comment by tituspijean** [comment]
Hello,
To see more verbose errors, you need to enable Flarum's `debug` mode, in `config.php`.

By the way, connecting with an admin account is usually not mandatory if users are allowed to log in the LDAP server with their own credentials. Note that the admin credentials are not stored securely in the database.

**Comment by Ornanovitch** [comment]
To see if something is wrong in the ldap query, you can also go into your ldap server, stop the service and start ldap with `slapd -d 8 -d 64 -d 32 -d 128 -d 256` (verbosity ++)

**Comment by tituspijean** [comment]
Closing due to lack of feedback.

**Comment by Marty** [comment]
I'm so sorry for not getting back to you. The pandemic really hurt the community I was building the forum for and all efforts were halted.

I put the forum in debug mode and got really useful insight into why it was failing and was able to solve it, thank you very much.
