### ISSUE TITLE
ldap query doesn't seems to look into subdirectories

### ISSUE THREAD

**Issue by Ornanovitch** [tituspijean/flarum-ext-auth-ldap#26]
Hey again !

So I'm just at a few steps from a perfect ldap config of flarum thanks to your plugin !
My last problem is that some of my users are registered into specific organizations (`ou=people,o=foo,dc=foo,dc=org`).

To login with those users, I have to adjust the `base_dn` like this : `ou=people,o=foo,dc=foo,dc=org` because if I attempt to connect with my normal `base_dn` (`ou=people,dc=foo,dc=org`), ldap queries doesn't search recursively. I imagine it's a simple parameter in the ldap module you are using but maybe am I wrong. According to several threads across the web, this seems to be a "scope" issue but I'm not sure.

Summary : 
user A is `uid=userA,ou=people,o=foo,dc=foo,dc=org`
user B is `uid=userB,ou=people,dc=foo,dc=org`

Both of them are in my filtered group (and the filter is working fine)

But user A can't login if `base_dn` is not `ou=people,o=foo,dc=foo,dc=org`
And user B can't login if `base_dn` is not `ou=people,dc=foo,dc=org`

Hope it's not too complicated...

**Comment by tituspijean** [comment]
It is getting more and more crazy for me to handle. ;p
Can you try converting your requirements into raw filters? It is not optimal but it may work:
Like putting `base_dn` as `dc=foo,dc=org` only, and putty in the filter something like `(|(memberOf=ou=people,o=foo,dc=foo,dc=org)(memberOf=ou=people,dc=foo,dc=org))`

**Comment by Ornanovitch** [comment]
You're right, I could use the filter now they are working !
I give it a try and let you know !

**Comment by Ornanovitch** [comment]
Unfortunately it doesn't work, I have the feeling it's a `base_dn` behavior. Put only the `dc=foo,dc=org` should handle a lot of config but when users are in separated departments (`o=foo`) it can't find them. Seems like a `o=foo` isn't handled like a group. It seems to be like a subdirectory of the `base_dn`, which can be reached by a ldap query with `LDAP_SCOPE_SUBTREE` argument (but I'm not sure 100%...)

But don't worry if it's to much to investigate, if I need to, I can easily put all my users at the ldap `base_dn` root until we find a solution !

I'll try to get ideas with the nextcloud ldap plugin, which doesn't care about the departments, ASAP. I'm not familiarized with ldap but I begin to understand some basics stuff...

Thanks again for your cool work, your plugin is becoming more usable with your last improvements :)

**Comment by tituspijean** [comment]
Actually we could extend the logic implemented in the linked PR above. @CodazziS has proposed to try logging in users either by `uid` or `mail`. We could add another loop with all the listed `base_dn`. After a quick look into Nextcloud's LDAP documentation, it seems they do just that.

In pseudo-code, it would be
```
foreach base_dn
    foreach uid or mail
         try connecting
```

**Comment by tituspijean** [comment]
@Ornanovitch, I have implemented what I wrote earlier. If you can, could you try it? I think replacing the contents of the PHP script should be enough. You need to separate your `base_dn` with semicolons.

**Comment by Ornanovitch** [comment]
Hi ! Thanks for this attempt :) 
I give it a try ASAP and I let you know !

**Comment by Ornanovitch** [comment]
Oops, I'm lost in those PHP changes : 
`Return value of TitusPiJean\Flarum\Auth\LDAP\Controllers\LDAPAuthController::handle() must be an instance of Psr\Http\Message\ResponseInterface, none returned`

Should I try with the CodazziS fork ?

**Comment by tituspijean** [comment]
The latest release (v0.1.0-beta.12-2) should work for you ;)

**Comment by Ornanovitch** [comment]
Okay ! It works like a charm :)

Caution : with this version, if I put a single `base_dn`, it does not work for me (but I need 3 so it works^^). So maybe there is a detail to fix.

**Comment by tituspijean** [comment]
Great to see that it works, and many thanks to @CodazziS, his contributions came with a great timing.

I do not have any issue with a single `base_dn`. Could you share the associated errors?

**Comment by Ornanovitch** [comment]
oops, I tried to reproduce the error but now everything works... maybe it was something else...
let's see in the future !

**Comment by tituspijean** [comment]
Matter seems to be resolved, enjoy!
