### ISSUE TITLE
Logging in fails

### ISSUE THREAD

**Issue by criskolkman** [tituspijean/flarum-ext-auth-ldap#30]
Hello,

I have installed and configured this extension, but when I try to login via LDAP I get the following error:

![image](https://user-images.githubusercontent.com/17678609/81827214-d73c9380-9538-11ea-9867-8a7287738400.png)

It would also be nice if the LDAP server name gets separated from the actual LDAP server that needs to be used, when you fill in an IP that is being used with **Log in with 1.2.3.4**

![image](https://user-images.githubusercontent.com/17678609/81827969-942ef000-9539-11ea-80e7-952ecb41e2fa.png)

**Comment by tituspijean** [comment]
Hello, thank you for installing and testing this extension.
As stated in the template issue, please provide a log, or a more descriptive error than your screenshot by enabling debugging on Flarum.

Regarding `LDAP server name`, that is purely cosmetic, and only used to display the login link. Do not confuse it with a server IP. Server IPs have to be put in `LDAP domains`.

You should check your `Filter to apply`, I think (but I am not a master in LDAP) that I will not like the space in "Global groups". You need to escape it at least with a backslash, or maybe with `\xx` where `xx` is its encoding.

**Comment by criskolkman** [comment]
> Hello, thank you for installing and testing this extension.
> As stated in the template issue, please provide a log, or a more descriptive error than your screenshot by enabling debugging on Flarum.
> 
> Regarding `LDAP server name`, that is purely cosmetic, and only used to display the login link. Do not confuse it with a server IP. Server IPs have to be put in `LDAP domains`.
> 
> You should check your `Filter to apply`, I think (but I am not a master in LDAP) that it will not like the space in "Global groups". You need to escape it at least with a backslash, or maybe with `\xx` where `xx` is its encoding.

I've tried to escape the space, didn't make any difference.
I then created a new group and user for the LDAP search (the "old" one also had spaces in de DN) and made sure both don't have any spaces in the DN, but it still doesn't make any difference.

**Comment by criskolkman** [comment]
So after enabling **debug** in `config.php` I see below error, it's giving an LDAP error but the error is empty?

![image](https://user-images.githubusercontent.com/17678609/82046033-71731780-96b0-11ea-953c-6734fa8a38f5.png)

**Comment by tituspijean** [comment]
On the left of what you screenshot, there is the stack trace of all the functions that lead to the error. Can you go further back in the list to find what triggered the exception?

**Comment by criskolkman** [comment]
> On the left of what you screenshot, there is the stack trace of all the functions that lead to the error. Can you go further back in the list to find what triggered the exception? You can click on each of them to have details.

Hello @tituspijean,

When I leave username and password empty I get below LDAP error (which seems obvious since I left the username empty):
![image](https://user-images.githubusercontent.com/17678609/82048956-d67d3c00-96b5-11ea-932e-cc423628b476.png)

When I do fill in my credentials the **LDAP error** is being triggered but with an empty response, I checked the functions on the left but not sure what to look for, all I see are entries like these:
![image](https://user-images.githubusercontent.com/17678609/82049149-2825c680-96b6-11ea-9e67-444528f3940c.png)

**Comment by tituspijean** [comment]
That's weird. :(

If you are willing to hack a little bit to help me debug, can you replace line 90 (a lone `}`) of `vendor/tituspijean/flarum-ext-auth_ldap/src/Controllers/LDAPAuthController.php` with the following and try again?

```php
} else {
die("Auth attempt failed");
}
```

On the other hand, can you check your LDAP server's logs to see anything useful?

**Comment by criskolkman** [comment]
@tituspijean After that modification I indeed get that error:

![image](https://user-images.githubusercontent.com/17678609/82051651-91a7d400-96ba-11ea-8ba8-a0698f58b67e.png)

**Comment by tituspijean** [comment]
OK thanks, we have thus pinpointed the issue there: `$connection->auth()->attempt($current_dn, $password, $bindAsUser = true)`. This fails somehow.

Can you replace the bit of code above with the following?
```php
} else {
die($current_dn);
}
```

I am assuming the password is correct, but can you check that `$current_dn` is a valid DN for your server?

Additional test: remove `, $bindAsUser = true`, as I think it is not necessary.

**Comment by criskolkman** [comment]
> ```
>  else {
> die($current_dn);
> }
> ```

I don't think the DN is correct, it is showing as `sAMAccountName=USERNAME,OU=domain,DC=com` and with email login it shows `mail=EMAIL@DOMAIN.COM,OU=domain,DC=com`.

**Comment by tituspijean** [comment]
I have just realized... what's the `(sAMAccountName=)` even for in your filter? You are demanding an empty field whenever you attempt to log in with that.

**Comment by criskolkman** [comment]
> ~I have just realized... what's the `(sAMAccountName=)` even for in your filter? You are demanding an empty field whenever you attempt to log in with that.~
> 
> Nevermind. Let's go back to basics. Remove the `filter`, and try to log in with whatever account you have. That will remove a layer of madness. :)

I don't have that in my filter:
![image](https://user-images.githubusercontent.com/17678609/82053258-5955c500-96bd-11ea-910e-a7382d7e36a8.png)

And I already tried it without the filter but now I tried again and getting the same result:
![image](https://user-images.githubusercontent.com/17678609/82053520-c8331e00-96bd-11ea-9cf6-6c5147567fa4.png)

**Comment by tituspijean** [comment]
> I don't have that in my filter:

Yes my bad, it gets added afterwards, and was empty because it is your example with empty credentials.

> The DN it's returning just doesn't seem to be correct.

What do you expect the DN to be looking like?

---
Paging @stevebauman, who offered to help with LdapRecord. :)

**Comment by criskolkman** [comment]
> > I don't have that in my filter:
> 
> Yes my bad, it gets added afterwards, and was empty because it is your example with empty credentials.
> 
> > The DN it's returning just doesn't seem to be correct.
> 
> What do you expect the DN to be looking like?
> 
> Paging @stevebauman, who offered to help with LdapRecord. :)

Well I've traced it back this far:

When I change the Base DN in the config to the exact OU the user is in, it seems the login is correct (eg the `die($current_dn);` is NOT being shown) but another error is being shown:

```
"LDAP error: (Unable to encode attribute [payload] for model [Flarum\User\RegistrationToken] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.)"
```

Also I had to change the **LDAP user search** to **cn**, because `mail=EMAIL@DOMAIN.COM,OU=...........` is not an AD DN.

It also seems that the base DN that is given is being searched for user accounts, but not the underlying OU's (which should be searched as well).

**Comment by stevebauman** [comment]
Hey @tituspijean!

This appears to be the issue:

```php
$current_dn = $searchUserField . "=" . $id . "," . $searchBaseDN; 
```

Source:
https://github.com/tituspijean/flarum-ext-auth-ldap/blob/11a2092b9639e7eeba324bde3c29d0bd72267221/src/Controllers/LDAPAuthController.php#L55

This will create an invalid search DN -- as we're seeing above, since @criskolkman is using `mail` as his `$searchUserField`.

A user is always identified by a common name (`cn`), such as:

```
cn=John Doe,ou=users,dc=local,dc=com
```

These `$searchUserFields` should be left out of the creation of the `base_dn` of the search. Instead, the `base_dn` should be left static to whatever the user sets in the configuration. An example search `base_dn` would be:

```
dc=local,dc=com
```

This would be sufficient, so all records are queried in the LDAP directory, and you can then use search filters to scope for specific results (as you're doing with `$query->rawFilter()` and `$query->where()` clauses.

Hope this helps!

**Comment by criskolkman** [comment]
> Hey @tituspijean!
> 
> This appears to be the issue:
> 
> ```
> $current_dn = $searchUserField . "=" . $id . "," . $searchBaseDN; 
> ```
> 
> Source:
> https://github.com/tituspijean/flarum-ext-auth-ldap/blob/11a2092b9639e7eeba324bde3c29d0bd72267221/src/Controllers/LDAPAuthController.php#L55
> 
> This will create an invalid search DN -- as we're seeing above, since @criskolkman is using `mail` as his `$searchUserField`.
> 
> A user is always identified by a common name (`cn`), such as:
> 
> ```
> cn=John Doe,ou=users,dc=local,dc=com
> ```
> 
> These `$searchUserFields` should be left out of the creation of the `base_dn` of the search. Instead, the `base_dn` should be left static to whatever the user sets in the configuration. An example search `base_dn` would be:
> 
> ```
> dc=local,dc=com
> ```
> 
> This would be sufficient, so all records are queried in the LDAP directory, and you can then use search filters to scope for specific results (as you're doing with `$query->rawFilter()` and `$query->where()` clauses.
> 
> Hope this helps!

This is exactly what I meant, thank you @CodazziS

**Comment by tituspijean** [comment]
Thanks for the impromptu lesson! I thought we could you whatever field in the base DN.
Can you test the following code then? Replace it for lines 53 to 97.

```
		foreach (explode(';', $searchBaseDNs) as $searchBaseDN) {
			foreach (explode(',', $searchUserFields) as $searchUserField) {

				if (!$this->settings->get($settingsPrefix . 'use_admin')) {
					$config['username'] = $id;
					$config['password'] = $password;
				}

				$connection = new Connection($config);
				try {
					if (!isset($filter) || $filter != '') {
						$user = $connection->query()
							->setDn($searchBaseDN)
							->where($searchUserField, '=', $id)
							->rawFilter($filter)
							->firstOrFail();
					} else {
						$user = $connection->query()
							->setDn($searchBaseDN)
							->where($searchUserField, '=', $id)
							->firstOrFail();
					}

					if ($connection->auth()->attempt($id, $password, $bindAsUser = true)) {
						$payload = (array)$user;
						return $this->response->make(
							'ldap',
							$id,
							function (Registration $registration) use ($user, $payload, $userLdapUsername, $userLdapMail) {
								$registration
									->provide('username', $user[$userLdapUsername][0])
									->provideTrustedEmail($user[$userLdapMail][0])
									//->provideAvatar($user->getJpegPhoto())
									->setPayload($payload);
							}
						);
					}

					break;
				} catch (Exception $e) {
					$ldapErrors[] = $e->getMessage();
				}
			}
		}
```

**Comment by criskolkman** [comment]
> foreach (explode(';', $searchBaseDNs) as $searchBaseDN) {
> 			foreach (explode(',', $searchUserFields) as $searchUserField) {
> 
> 				if (!$this->settings->get($settingsPrefix . 'use_admin')) {
> 					$config['username'] = $id;
> 					$config['password'] = $password;
> 				}
> 
> 				$connection = new Connection($config);
> 				try {
> 					if (!isset($filter) || $filter != '') {
> 						$user = $connection->query()
> 							->setDn($searchBaseDN)
> 							->where($searchUserField, '=', $id)
> 							->rawFilter($filter)
> 							->firstOrFail();
> 					} else {
> 						$user = $connection->query()
> 							->setDn($searchBaseDN)
> 							->where($searchUserField, '=', $id)
> 							->firstOrFail();
> 					}
> 
> 					if ($connection->auth()->attempt($user['distinguishedname'], $password, $bindAsUser = true)) {
> 						$payload = (array)$user;
> 						return $this->response->make(
> 							'ldap',
> 							$id,
> 							function (Registration $registration) use ($user, $payload, $userLdapUsername, $userLdapMail) {
> 								$registration
> 									->provide('username', $user[$userLdapUsername][0])
> 									->provideTrustedEmail($user[$userLdapMail][0])
> 									//->provideAvatar($user->getJpegPhoto())
> 									->setPayload($payload);
> 							}
> 						);
> 					}
> 
> 					break;
> 				} catch (Exception $e) {
> 					$ldapErrors[] = $e->getMessage();
> 				}
> 			}
> 		}

Using this code is resulting in the same empty LDAP error:
`"LDAP error: ()"`

**Comment by criskolkman** [comment]
Oh and @tituspijean please be aware that LDAP for Active Directory (which I am using) probably differs from OpenLDAP queries. 
I have never worked with OpenLDAP before but it could be that your code works fine for OpenLDAP but it doesn't for AD LDAP.

**Comment by tituspijean** [comment]
Hi @criskolkman, can you try the testing branch?

`composer require tituspijean/flarum-ext-auth-ldap:dev-testing --prefer-dist`

Can you try first without filter, then with it?

**Comment by criskolkman** [comment]
> `composer require tituspijean/flarum-ext-auth-ldap:dev-testing --prefer-dist`

Hello @tituspijean,

I now get the following error after logging in:
`"LDAP error: (Unable to encode attribute [payload] for model [Flarum\User\RegistrationToken] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.)"`

**Comment by tituspijean** [comment]
Using the debugger, can you pinpoint which variable contains the utf-8 characters the error is referring to?

**Comment by criskolkman** [comment]
> Using the debugger, can you pinpoint which variable contains the utf-8 characters that the error is referring to? And which characters are causing the issue?

@tituspijean Not really sure where to look for that. Other than that error I'm only getting messages like:

`Laminas\Diactoros\ServerRequest {#1655}`

And:
`Laminas\Diactoros\ServerRequest {#1655}
[]`

`Laminas\Diactoros\ServerRequest {#1646}
Closure(ServerRequestInterface $request, array $routeParams) {#619 …4}`

**Comment by tituspijean** [comment]
I think I found where the issue was. Can you delete the extension directory and perform the `require` command again?

Note that I was confusing username and common name. For registration, Flarum wants a username (`uid` for example), not something that can contain a space like `cn`. Check the extension config panel, specifically the last field.

**Comment by criskolkman** [comment]
> I think I found where the issue was. Can you delete the extension directory and perform the `require` command again?
> 
> Note that I was confusing username and common name. For registration, Flarum wants a username (`uid` for example), not something that can contain a space like `cn`. Check the extension config panel, specifically the last field.

For a username you should always use the AD attribute **sAMAccountName**, I don't think that ever will contain a space.
When you have an AD login for for example the company you work for, your login name (sAMAccountName) will most likely be something with your first and last name, in my case that would be something like **ckolkman** or **cris.kolkman**.

My config:
![image](https://user-images.githubusercontent.com/17678609/82124273-42d36a80-979e-11ea-8431-3975fbc1c379.png)

**Comment by criskolkman** [comment]
@tituspijean After removing the directory and re-installing I'm getting the same error:

`"LDAP error: (Unable to encode attribute [payload] for model [Flarum\User\RegistrationToken] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.)"`

**Comment by criskolkman** [comment]
After changing the **LDAP user displayName field** to **sAMAccountName** (which is not the displayname but the login, but just did it to test) I get the following error:

`"Argument 2 passed to Flarum\Forum\Auth\ResponseFactory::make() must be of the type string, null given, called in /var/www/clients/client2/web9/web/vendor/tituspijean/flarum-ext-auth-ldap/src/Controllers/LDAPAuthController.php on line 83 ◀"`

**Comment by tituspijean** [comment]
Regarding your comment about `sAMAccountName`, that would be completely dependent on how the LDAP tree is set up. In my test server case, I do not have such attribute.

I think the latest commit was not installed. You should get from composer:
```
Package operations: 1 install, 0 updates, 0 removals
  - Installing tituspijean/flarum-ext-auth-ldap (dev-testing c380ff0): Downloading (100%)
```

![image](https://user-images.githubusercontent.com/8769166/82124475-88446780-979f-11ea-87c1-d3db279e5edc.png)

**Comment by criskolkman** [comment]
> Edit: did not see the comment above. I think Flarum does not update locales right away. Investigating...
> 
> Regarding your comment about `sAMAccountName`, that would be completely dependent on how the LDAP tree is set up. In my test server case, I do not have such attribute.
> 
> I think the latest commit was not installed. You should get from composer:
> 
> ```
> Package operations: 1 install, 0 updates, 0 removals
>   - Installing tituspijean/flarum-ext-auth-ldap (dev-testing c380ff0): Downloading (100%)
> ```
> 
> ![image](https://user-images.githubusercontent.com/8769166/82124475-88446780-979f-11ea-87c1-d3db279e5edc.png)

@tituspijean Are you using OpenLDAP as a test server? Like I said I'm using Active Directory (Windows Server) with LDAP, you probably want 2 different configs for them because **sAMAccountName** is ALWAYS an attribute in AD.
The other web app I'm using (from which I pasted part of the config in one of my previous posts) is using different config files for OpenLDAP and Active Directory LDAP.

My update did work, I have the same options as in your screenshot (see my last screenshot).
The **uid** attribute you are using is **not** an AD attribute, in AD that's **sAMAccountName**.

**Comment by tituspijean** [comment]
I understand you have an OpenLDAP server. I want to make this extension as versatile as possible, hence the configurable username/id field.

I have however no spare time to investigate all specific use of the extension, so let me rely on your tests to make it compatible with OpenLDAP.

> `"Argument 2 passed to Flarum\Forum\Auth\ResponseFactory::make() must be of the type string, null given, called in /var/www/clients/client2/web9/web/vendor/tituspijean/flarum-ext-auth-ldap/src/Controllers/LDAPAuthController.php on line 83 ◀"`

According to my code, argument 2 of `make()` is `$user[$userLdapUsername][0]` which should be your user's `sAMAccountName`. At this stage of the code, it should not be `null`.

Can you add between line 73 and 74 the following code? It should print out information regarding your user. Please check for any inconsistency.
```
						echo('<pre>');
						print_r($user);
						print_r($userLdapUsername . ": " . $user[$userLdapUsername][0]);
						echo('</pre>');
```

**Comment by criskolkman** [comment]
> I understand you have an OpenLDAP server, however I do not. I want to make this extension as versatile as possible, hence the configurable username/id field.
> 
> I have however no spare time to investigate all specific use of the extension, so let me rely on your tests to make it compatible with OpenLDAP.

Let me make clear again, I'm **not** using OpenLDAP but I'm using Active Directory LDAP.
Adding your code seems to return correct values, exept for below 2 screenshots.

![image](https://user-images.githubusercontent.com/17678609/82125750-6e5b5280-97a8-11ea-9e20-2617a40e0c5d.png)

![image](https://user-images.githubusercontent.com/17678609/82125756-74513380-97a8-11ea-8363-315357ead4a3.png)

**Comment by Eli0tt** [comment]
Hello, I'm also using Active Directory and I'm getting exactly the same error: "LDAP error: ()"

A solution?

**Comment by tituspijean** [comment]
@criskolkman Damn, I should proofread.
Can you check in the array above that there is a `sAMAccountName` key, or maybe in lowercase?

---
@Eli0tt, we are working on it.

**Comment by criskolkman** [comment]
> @criskolkman Damn, I should proofread.
> Can you check in the array above that there is a `sAMAccountName` key, or maybe in lowercase?
> 
> @Eli0tt, we are working on it.

@tituspijean There is a sAMAccountName entry:
![image](https://user-images.githubusercontent.com/17678609/82199944-a96f9a00-98fe-11ea-8d37-4c2c4ddcda9f.png)

But the last `print_r` of the extra code you asked me to add (`print_r($userLdapUsername . ": " . $user[$userLdapUsername][0]);`) does not return the username:
![image](https://user-images.githubusercontent.com/17678609/82200106-e471cd80-98fe-11ea-9258-88fa20d06e2a.png)

**Comment by tituspijean** [comment]
Good, so the issue lies in the capitalization then. I have pushed a commit on the testing branch. Can you do the same test as before, to redownload the extension?

**Comment by criskolkman** [comment]
@tituspijean Changing the config to below screenshot (note that **...** is all lowercase) does seem to fix the login problem, but get's me back to below error.

![image](https://user-images.githubusercontent.com/17678609/82201662-0409f580-9901-11ea-9562-8251feef5710.png)

`"LDAP error: (Unable to encode attribute [payload] for model [Flarum\User\RegistrationToken] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.)"`

**Comment by criskolkman** [comment]
> Good, so the issue lies in the capitalization then. I have pushed a commit on the testing branch. Can you do the same test as before, to redownload the extension?

@tituspijean Redownload now gives below error:

```
composer require tituspijean/flarum-ext-auth-ldap:dev-testing --prefer-dist
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tituspijean/flarum-ext-auth-ldap dev-testing -> satisfiable by tituspijean/flarum-ext-auth-ldap[dev-testing].
    - tituspijean/flarum-ext-auth-ldap dev-testing requires flarum/core >=0.1.0-beta.12 <=0.1.0-beta.13 -> satisfiable by flarum/core[v0.1.0-beta.12, v0.1.0-beta.13] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

**Comment by tituspijean** [comment]
Try `composer require tituspijean/flarum-ext-auth-ldap:dev-testing --prefer-dist --dev`

**Comment by criskolkman** [comment]
> composer require tituspijean/flarum-ext-auth-ldap:dev-testing --prefer-dist --dev

Getting the same error.

**Comment by tituspijean** [comment]
And now we are struggling with composer...
`composer require tituspijean/flarum-ext-auth-ldap`
and replace file `vendor/tituspijean/flarum-ext-auth-ldap/src/Controllers/LDAPAuthController.php` with the one here: https://github.com/tituspijean/flarum-ext-auth-ldap/blob/testing/src/Controllers/LDAPAuthController.php

**Comment by criskolkman** [comment]
> And now we are struggling with composer...
> `composer require tituspijean/flarum-ext-auth-ldap`
> and replace file `vendor/tituspijean/flarum-ext-auth-ldap/src/Controllers/LDAPAuthController.php` with the one here: https://github.com/tituspijean/flarum-ext-auth-ldap/blob/testing/src/Controllers/LDAPAuthController.php

No sorry I made a mistake (was trying to run the composer command in the wrong directory...).

Now after logging in I'm getting below error:
`"Argument 4 passed to Flarum\User\RegistrationToken::generate() must be of the type array, string given, called in /var/www/clients/client2/web9/web/vendor/flarum/core/src/Forum/Auth/ResponseFactory.php on line 51 ◀"`

**Comment by tituspijean** [comment]
OK thanks, I have made the token an array. Try again? 🤞

**Comment by criskolkman** [comment]
> OK thanks, I have made the token an array. Try again? 🤞

@tituspijean Logging in is working now!
Only thing what would be nice is: Now the sAMAccountName is being used as displayName because the displayName is not configurable anymore.

**Comment by tituspijean** [comment]
Glad to hear it!

The `displayName` was remaining from an older test, and it seems it is not fully implemented in Flarum for the time being. Refer to #10 and the upstream issue linked there. To identify users, we need a string that cannot be changed (ie `uid` or `sAMAccountname`). Flarum does not offer ways to add a display name programmatically yet.

**Comment by criskolkman** [comment]
> Glad to hear it!
> 
> The `displayName` was remaining from an older test, and it seems it is not fully implemented in Flarum for the time being. Refer to #10 and the upstream issue linked there. To identify users, we need a string that cannot be changed (ie `uid` or `sAMAccountname`). Flarum does not offer ways to add a display name programmatically yet.

Thank you, hope they will implement this in Flarum soon then :)

**Comment by tituspijean** [comment]
Thank *you* very much for helping me debug the issue. It helped me make the logging in method more robust and versatile.

@stevebauman, thanks for dropping by and for your explanation!

**Comment by tituspijean** [comment]
By the way @criskolkman, you can switch back to the non dev version with a standard `require`, without specifying the branch name.

**Comment by criskolkman** [comment]
> By the way @criskolkman, you can switch back to the non dev version with a standard `require`, without specifying the branch name.

Thank you, switched back to the standard branch.
