### ISSUE TITLE
Translate extension

### ISSUE THREAD

**Issue by Eli0tt** [tituspijean/flarum-ext-auth-ldap#32]
Hello,

Simple question, my Flarum is in French, and I would like to know how can I translate the LDAP extension?
I tried to modify the .yml file directly, but the translation is only done in the English version of the site.
I tried to add a fr.yml file, but the same thing happens

**Comment by tituspijean** [comment]
Hi, I have just pushed a commit adding French translation in the `testing` branch. Can you check it out?
`composer require tituspijean/flarum-ext-auth-ldap:dev-testing`
You may need to `php flarum cache:clear` too.

**Comment by Eli0tt** [comment]
Hi, it's working perfectly! :)

**Comment by tituspijean** [comment]
Do not forget to switch back to standard branch. :) Thank you for trying it out!
