### ISSUE TITLE
beta 14 compatibility

### ISSUE THREAD

**Issue by Ornanovitch** [tituspijean/flarum-ext-auth-ldap#38]
Hey there !

Do you have any plans concerning compatibility with beta 14 ?

Regards,

**Comment by tituspijean** [comment]
I do, but have no time until next weekend :)

**Comment by CodazziS** [comment]
Hello @tituspijean 
Do you need help to migrate to beta 15 ?

**Comment by tituspijean** [comment]
Ouch, I completely forgot about beta 14 and missed beta 15.
If you are willing to do it, you are most welcome. I am a tad taken up by work nowadays.

**Comment by CodazziS** [comment]
Hello @tituspijean I just add PR #42 . 
I test it for ldap connexion, maybe need more tests.

Issue #41 id not fixed in this PR. I will try to fix-it after beta 15 support

**Comment by tituspijean** [comment]
Solved in #47.
