### ISSUE TITLE
Does not support v0.1.0-beta.16

### ISSUE THREAD

**Issue by MrVBian** [tituspijean/flarum-ext-auth-ldap#49]
![image](https://user-images.githubusercontent.com/37790267/118373065-471ba900-b5e7-11eb-94d6-3a48af1ffb96.png)

Thank you very much for your work. Would you consider upgrading to be compatible with v0.1.0-beta.16?

**Comment by tituspijean** [comment]
I have already released a [version for beta 16](https://github.com/tituspijean/flarum-ext-auth-ldap/releases/tag/v0.1.0-beta.16-1). Can you try requiring this specific tag "v0.1.0-beta.16-1"?
