### ISSUE TITLE
Use this plugin without sign in permission

### ISSUE THREAD

**Issue by sprnza** [tituspijean/flarum-ext-auth-ldap#52]
Hi there!
Thank you for this wonderful extension!
What I try to do is to use it with "Sign In" permission set to Closed. When a user tries to login the first time one's being redirected to sign in form, wich fails with the permission set to Closed. 
Is there a way to workaround this somehow?

**Comment by tituspijean** [comment]
It is more a matter of disabling the core registration endpoints. I can try to have a look into it, but I am not *that* knowledgeable. Contributions are welcome.

**Comment by botagas** [comment]
I have hidden the login buttons entirely with this:
```

.item-signUp .Button--link {
display: none;
}
.item-logIn .Button--link {
display: none;
}
```

However, it is only a cosmetic workaround.
